name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build

    - name: Verify Build Directory
      run: ls -la build

    - name: Test Tar Creation
      run: tar -czf /tmp/test.tar.gz build/*



    - name: Test SFTP Connection
      run: |
        sshpass -p "${{ secrets.SFTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} "ls -la /home/crypto_bro"
    
    - name: Deploy to SFTP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        source: "build/*"
        target: "/home/crypto_bro/optom"
        debug: true
        command_timeout: 600s
        timeout: 300s
