name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build
    
    - name: Deploy to SFTP
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: build/
        remote_path: /home/crypto_bro/optom
        remote_host: ${{ secrets.SFTP_HOST }}
        remote_user: ${{ secrets.SFTP_USERNAME }}
        remote_pass: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}